name: Update asset/readme on WordPress.org

on:
  workflow_dispatch:
    inputs:
      ignoreOtherFiles:
        description: 'Ignore other file changes'
        required: true
        type: boolean
        default: false
  push:
    branches:
    - trunk

jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node version
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Build
      run: |
        npm run build-release

    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: ad-refresh-control
        IGNORE_OTHER_FILES: ${{ inputs.ignoreOtherFiles || false }}
